version: 2.1

workflows:
  test-deploy:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: circleci/node:erbium-bullseye-browsers-legacy
    steps:
      - checkout
      - run:
          name: Install dependency
          command: npm install
      - run:
          name: Run Tests
          command: npm run test
      - run: node --version
