version: 2.1

workflows:
  test-deploy:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: circleci/node:erbium-bullseye-browsers-legacy
    steps:
      - checkout
      - run: node --version
